name: Build

on: [push]

env:
  api_key: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --user pipx
        python -m pipx ensurepath
    - name: Install poetry
      run: |
        pipx install poetry==1.2.0
    - name: Authenticate
      run: |
        poetry config pypi-token.pypi $api_key
    - name: Build and Publish
      run: |
        poetry build
        poetry publish
