name: Build and Deploy using Poetry

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install pipx
      run: |
        python -m pip install pipx
        
    - name: Install poetry
      run: |
        pipx install poetry==1.2.0

    - name: Update version in pyproject.toml
      run: |
        version=$(date +%Y%m%d%H%M%S)
        echo "Updating version to $version"
        sed -i "s/^version.*/version = \"$version\"/" pyproject.toml

    - name: Build package
      run: poetry build

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
      env:
        PYPI_PACKAGE: ${{ env.GITHUB_WORKSPACE }}/dist/*
        
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pipx
      run: |
        python -m pip install pipx
        
    - name: Install poetry
      run: |
        pipx install poetry==1.2.0

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: dist

    - name: Publish to PyPI
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_API_KEY }}
        poetry publish
