name: Continuous Integration (CI)

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Set up Doxygen 
        uses: mattnotmitt/doxygen-action@v1.9.5
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx breathe
          
      - name: Update docs
        run: |
          sphinx-build -b html . docs
